/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002113",
        "on-tertiary": "#68000a",
        "surface-container-low": "#171b26",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-container": "#5c0008",
        "surface-variant": "#313540",
        "on-primary-container": "#00285d",
        "inverse-primary": "#005ac2",
        "surface-container-high": "#262a35",
        "error": "#ffb4ab",
        "on-primary-fixed": "#001a42",
        "secondary-fixed-dim": "#4edea3",
        "outline": "#8c909f",
        "on-secondary-fixed-variant": "#005236",
        "surface-tint": "#adc6ff",
        "primary": "#adc6ff",
        "secondary": "#4edea3",
        "surface-container-highest": "#313540",
        "outline-variant": "#424754",
        "inverse-surface": "#dfe2f1",
        "inverse-on-surface": "#2c303b",
        "on-error-container": "#ffdad6",
        "background": "#0f131d",
        "tertiary": "#ffb3ad",
        "tertiary-container": "#ff5451",
        "secondary-fixed": "#6ffbbe",
        "on-error": "#690005",
        "secondary-container": "#00a572",
        "on-surface": "#dfe2f1",
        "error-container": "#93000a",
        "primary-container": "#4d8eff",
        "primary-fixed": "#d8e2ff",
        "surface-bright": "#353944",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary-fixed-variant": "#930013",
        "surface-container": "#1c1f2a",
        "on-background": "#dfe2f1",
        "on-secondary": "#003824",
        "tertiary-fixed": "#ffdad7",
        "surface-container-lowest": "#0a0e18",
        "on-tertiary-fixed": "#410004",
        "on-primary": "#002e6a",
        "surface": "#0f131d",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-dim": "#0f131d",
        "on-secondary-container": "#00311f",
        "primary-fixed-dim": "#adc6ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "unit": "4px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "max-width": "1440px"
      },
      fontFamily: {
        "headline-lg": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "display-xl": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "code-mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["15px", { lineHeight: "24px", fontWeight: "600" }],
        "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "code-mono": ["13px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
